import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#fefcff",
        "inverse-primary": "#6bd8cb",
        "secondary-fixed": "#b7eaff",
        "inverse-surface": "#233144",
        "on-secondary-container": "#006077",
        "tertiary-fixed": "#dae2fd",
        "surface-tint": "#006a61",
        "on-surface-variant": "#3d4947",
        "secondary-fixed-dim": "#6cd3f7",
        background: "#f8f9ff",
        "surface-variant": "#d5e3fc",
        surface: "#f8f9ff",
        secondary: "#006780",
        "on-primary-fixed-variant": "#005049",
        "surface-container": "#e6eeff",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed-dim": "#bec6e0",
        "surface-bright": "#f8f9ff",
        "on-primary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#76dcff",
        "surface-container-highest": "#d5e3fc",
        "primary-fixed-dim": "#6bd8cb",
        "surface-container-high": "#dce9ff",
        "primary-fixed": "#89f5e7",
        "on-secondary-fixed": "#001f28",
        "primary-container": "#008378",
        "on-surface": "#0d1c2e",
        outline: "#6d7a77",
        "tertiary-container": "#6c748b",
        "on-secondary-fixed-variant": "#004e61",
        "on-tertiary-fixed-variant": "#3f465c",
        "outline-variant": "#bcc9c6",
        "on-primary-container": "#f4fffc",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#131b2e",
        "on-error": "#ffffff",
        tertiary: "#545c72",
        primary: "#00685f",
        "on-primary-fixed": "#00201d",
        "surface-dim": "#ccdbf3",
        "on-background": "#0d1c2e",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        lg: "40px",
        sm: "12px",
        "margin-mobile": "16px",
        gutter: "24px",
        base: "8px",
        "margin-desktop": "48px",
        xs: "4px",
        xl: "64px",
      },
      fontFamily: {
        "headline-xl": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
